remote_theme: samarsault/texture


texture:
  title: Marika Girard
  tagline: Ergoth√©rapeute
  date_format: "%b %-d, %Y"

  style: black

  showPicker: true

  social_links:
    #twitter: thelehhman
    #github:  thelehhman
    #linkedIn: in/thelehhman # format: locale/username


